export { Home } from './Home';
export { AboutUs } from './AboutUs';
export { AboutOverview } from './AboutOverview';
export { AboutApproach } from './AboutApproach';
export { AboutManagement } from './AboutManagement';
export { AboutSuccessStories } from './AboutSuccessStories';
export { ServicesPage } from './ServicesPage';
export { EmployeeBenefits } from './Services/EmployeeBenefits';
export { Insights } from './Insights';
export { InsightsCategory } from './InsightsCategory';
export { Careers } from './Careers';
export { ContactUs } from './ContactUs';
export { default as InsuranceConsulting } from './Services/InsuranceConsulting';
export { RetirementConsulting } from './Services/RetirementConsulting';
export { default as BenefitConsulting } from './BenefitConsulting';